export default {

    cn: {
        sorry: '抱歉',
        btn_ok: 'OK',
        change_desc: '剩余机会',
        details: '规则',
        congrats: '恭喜',
        lott_check_now: '立即查看',
        go_shop: '去购物',
        lott_fail: '抽奖失败',
        lott_start: '将要开始',
        free_item: '免邮',
        wind_free: '免邮提示',
        lott_point: '积分',
        win_point: '积分提示',
        coupon_text_decrease: '满减券',
        coupon_text_percent: '百分比券',
        win_pri_decrease: '满减券提示',
        win_pri_percent: '百分比券提示',
        no_chances_one: '分享文案1',
        no_chances_two: '分享文案2',
        lott_end: '活动结束'
    },
    en: {
        sorry: 'Oops, good luck next time!',
        btn_ok: 'OK',
        change_desc: 'XX chances left',
        details: 'DETAILS',
        congrats: 'Congratulations',
        lott_check_now: 'Check Now',
        go_shop: 'Go Shopping',
        lott_fail: 'If the lucky draw fails, please try again later. ',
        lott_start: 'The promotion will start in',
        free_item: 'a free item',
        wind_free: 'You won <span>a FREE item.</span> Just use the coupon issued to your account to purchase it for free.',
        lott_point: 'XX D-Points',
        win_point: 'You won <span>XX D</span> Points. You can check it in your account.</span>',
        coupon_text_decrease: 'a QQXX off QQYY Coupon',
        coupon_text_percent: 'a XX% off QQYY Coupon',
        win_pri_decrease: 'You won a <span>QQXX off QQYY coupon.</span> You can check it in your account.',
        win_pri_percent: 'You won a <span>XX% off QQYY coupon.</span> You can check it in your account.',
        no_chances_one: 'You\'ve used up your chance of playing. <br>Share to get extra chances!',
        no_chances_two: 'You\'ve used up your chances today.<br> Please come back tomorrow.',
        lott_end: 'Sorry, promotion ended.'
    },
    fr: {
        sorry: 'Désolé, vous n\'avez pas gagné de récompense cette fois. Essayez à nouveau plus tard.',
        btn_ok: 'OK',
        change_desc: 'XX chances restants',
        details: 'DETAILES',
        congrats: 'Félicitations',
        lott_check_now: 'Vérifiez-le',
        go_shop: 'Shoppez',
        lott_fail: 'Si le tirage au sort échoue, merci d\'essayer à nouveau plus tard.',
        lott_start: 'L\'événement commencera en',
        free_item: 'un article gratuit',
        wind_free: 'Vous avoir gagné <span>un article GRATUIT.</span> Utilisez le coupon envoyé dans votre compte pour l\'acheter grattuitement.',
        lott_point: 'XX Points D',
        win_point: 'Vous avez gagné <span>XX Points D </span>en récompense. Veuillez les vérifier dans votre compte.',
        coupon_text_decrease: 'un coupon de YYQQ - XXQQ',
        coupon_text_percent: 'un coupon de -XX%',
        win_pri_decrease: 'Vous avez gagné un <span>coupon de -XXQQ DÈS YYQQ DÈS</span> en récompense. Veuillez le vérifier dans votre compte.',
        win_pri_percent: 'Vous avez gagné un <span>coupon de XX% DE REMISE YYQQ</span> en récompense. Veuillez le vérifier dans votre compte.',
        no_chances_one: 'Vous n\'avez plus aucune chance pour un tirage au sort maintenant, merci de partager pour obtenir un chance.',
        no_chances_two: 'Vous avez utilisé toutes vos opportunités aujourd\'hui. <br>Revenez demain.',
        lott_end: 'Désolé, l\'événement est fini.'
    }

};
