#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link      http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license   http://www.yiiframework.com/license/
 */
define('SHOEDBSQL', $_GET['debug'] ?? 0 == 1);
defined('YII_ENV') || define('YII_ENV', empty($argv[2]) ? 'dev' : $argv[2]);
defined('YII_DEBUG') || define('YII_DEBUG', 0 === strpos(YII_ENV, 'dev'));
defined('APP_PATH') || define('APP_PATH', __DIR__);
defined('APOLLO_CONFIG_PATH') || define('APOLLO_CONFIG_PATH', '/data/www/apollo-config');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require(__DIR__ . '/base/CommonFunction.php');

if(is_file(__DIR__ . '/config/console.' . YII_ENV . '.php')) {
    $config = require __DIR__ . '/config/console.' . YII_ENV . '.php';
}

function app()
{
    return Yii::$app;
}

$application = new yii\console\Application($config);
$exitCode = $application->run();

exit($exitCode);
